global:
 resolve_timeout: 1m
 slack_api_url: 'https://hooks.slack.com/services/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'
 
route:
 receiver: 'slack-notifications'
 
receivers:
  - name: 'slack-notifications'
    slack_configs:
     - channel: '#alertas-alertmanager'
       send_resolved: true
       title: |-
        [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }} for {{ .CommonLabels.job }}
        {{- if gt (len .CommonLabels) (len .GroupLabels) -}}
          {{" "}}(
          {{- with .CommonLabels.Remove .GroupLabels.Names }}
            {{- range $index, $label := .SortedPairs -}}
              {{ if $index }}, {{ end }}
              {{- $label.Name }}="{{ $label.Value -}}"
            {{- end }}
          {{- end -}}
          )
        {{- end }}
       text: >-
        {{ range .Alerts -}}
        *Alert:* {{ .Annotations.title }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}
        *Description:* {{ .Annotations.description }}
        *Details:*
          {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
          {{ end }}
        {{ end }}

# global:
#   resolve_timeout: 1m
#   slack_api_url: 'https://hooks.slack.com/services/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'

#   route:
#   receiver: 'slack-notifications'

#   receivers:
#   - name: 'slack-notifications'
#   slack_configs:
#   - channel: '#alertas-alertmanager'
#     send_resolved: true
#     icon_url: https://avatars3.githubusercontent.com/u/3380462
    
# global:
#  resolve_timeout: 1m

# route:
#  receiver: 'email-notifications'

# receivers:
#  - name: 'email-notifications'
#    email_configs:
#    - to: guilherme@meucredere.com.br
#      from: monitoringtestcrd@gmail.com
#      smarthost: smtp.gmail.com:587
#      auth_username: monitoringtestcrd@gmail.com
#      auth_identity: monitoringtestcrd@gmail.com
#      auth_password: 


