groups:
- name: alert.rules
  rules:
  
  - alert: InstanceDown
    expr: up {stack="monitoring"} == 0
    for: 1m
    labels:
      severity: "critical"
    annotations:
      summary: "Endpoint {{ $labels.instance }} down"
      description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minutes."

  - alert: HostOutOfMemory
    expr: node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes *100  < 10
    for: 3m
    labels:
      severity: warning
    annotations:
      summary: "Host out of memory (instance {{ $labels.instance }})"
      description: "Node memory is filling up (< 25% left)\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"


  - alert: HostOutOfDiskSpace
    expr: (node_filesystem_avail_bytes{mountpoint="/"} *100) / node_filesystem_size_bytes{mountpoint="/"} < 10
    for: 1s
    labels:
      severity: warning
    annotations:
      summary: "Host out of disk space (instance {{ $labels.instance }})"
      description: "Disk is almost full (< 90% left)\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"


  - alert: HostHighCpuLoad
    expr: (sum by (instance)(irate(node_cpu_seconds_total{job="node_exporter",mode="idle" }[5m]))) > 80
    for: 3m
    labels:
      severity: warning
    annotations:
      summary: "Host high CPU load (instance {{ $labels.instance }})"
      description: "CPU load is > 80%\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"


  - alert: DominioDown
    expr: probe_success{job="blackbox-https"} < 1
    for: 3m
    labels:
      severity: warning
    annotations:
      summary: "The domain is down (instance {{ $labels.instance }}) is down"
      description: " The domain is down (instance {{ $labels.instance }}) is down - VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
      