- name: create blackbox system group
  user:
     name: blackbox_exporter
     shell: /bin/false
     system: true
     create_home: no

- name: Download and unarchive 
  unarchive:
    src: https://github.com/prometheus/blackbox_exporter/releases/download/v0.19.0/blackbox_exporter-0.19.0.linux-amd64.tar.gz
    dest: /etc
    remote_src: yes

- name: Copy the unzipped files to the bin folder
  ansible.builtin.copy:
    remote_src: yes
    src: /etc/blackbox_exporter-0.19.0.linux-amd64/
    dest: /usr/local/bin/
    owner: blackbox_exporter
    group: blackbox_exporter
    mode: u+x,g+x,o+x

- name: creating directory
  file:
    path: "/etc/blackbox_exporter"
    state: directory
    owner: blackbox_exporter
    mode: 0755

- name: Create blackbox.yml configuration file
  ansible.builtin.copy:
    src: blackbox.yml
    dest: /etc/blackbox_exporter/blackbox.yml
    owner: blackbox_exporter
    group: blackbox_exporter

- name: Create blackbox.service configuration file
  ansible.builtin.copy:
    src: blackbox_exporter.service
    dest: /etc/systemd/system
    owner: blackbox_exporter
    group: blackbox_exporter
    mode: 0755

- name: daemon-reload
  shell: systemctl daemon-reload


- name: start blackbox
  shell: systemctl restart blackbox_exporter

- name: Configure to start blackbox with machine start
  service: 
    name: blackbox_exporter
    enabled: yes