- hosts: webserver
  vars:
    ansible_python_interpreter: /usr/bin/python3
    prometheus_version: 2.32.1
  become: yes
  remote_user: admin
  connection: local 
  roles:
    - role: grafana
      tags: grafana
    - role: node
      tags: node
    - role: grafana_plugins
      tags: grafana
    - role: prometheus
      tags: prometheus
    - role: alertmanager
      tags: alertmanager
    - role: blackbox
      tags: blackbox
    - role: process_exporter
      tags: process_exporter
    
